# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/sm6150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sm6150-common)

endif
